In [13]:
import pickle
import numpy as np

In [14]:
walks = pickle.load(open('data/walks.pkl', 'rb'))

In [56]:
walk_lens = [len(walk) for walk in walks]
max(walk_lens), np.average(walk_lens), np.median(walk_lens)

(12, 2.7193938197609735, 3.0)

In [52]:
np.argmax(walk_lens)

2156016

In [53]:
walks[2156016]

array([13128,  7389,  1220, 15862,  2189, 10801,  9943,  1288,  1288,
       15723,  4510,  3442], dtype=int32)

In [17]:
walks

[array([22493, 14175], dtype=int32),
 array([22493], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493], dtype=int32),
 array([22493], dtype=int32),
 array([22493], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493], dtype=int32),
 array([22493], dtype=int32),
 array([22493], dtype=int32),
 array([22493], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493], dtype=int32),
 array([22493], dtype=int32),
 array([22493, 14175], dtype=int32),
 array([22493], dtype=int

In [18]:
from ctdne import EmbeddingModel

embedding_model = EmbeddingModel(
    num_walks=50,
    len_walk=100,
    random_picker_type="Linear",
    d_embed=128,
)

In [19]:
from test import read_data

data = read_data()
embedding_model.add_temporal_edges(data)

In [24]:
from networkx.classes import DiGraph

networkx_graph: DiGraph = embedding_model.temporal_walk.to_networkx()

In [54]:
def get_max_path_length(node, current_depth, current_timestamp):
    edges = networkx_graph.edges(node, data=True)
    max_path_length = current_depth

    for edge in edges:
        next_node = edge[1]
        timestamp = edge[2]['timestamp']

        if timestamp > current_timestamp:
            current_path_len = get_max_path_length(
                next_node, current_depth + 1, timestamp
            )
            max_path_length = max(max_path_length, current_path_len)

    return max_path_length

nodes = networkx_graph.nodes()
max_path_lens = [
    get_max_path_length(node, 0, float('-inf')) for node in nodes
]

In [57]:
max(max_path_lens), np.average(max_path_lens), np.median(max_path_lens)

(16, 3.7838710835157734, 3.0)